name: Deploy PWA to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-disabled: true # Временно отключаем кэш из-за сбоев GitHub

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build Wasm
        run: ./gradlew :app:wasmJsBrowserDistribution --no-daemon --stacktrace

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: app/build/dist/wasmJs/productionExecutable
          branch: gh-pages
